name: Update

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    name: "Update data"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-dev

      - name: Run script
        run: poetry run get_cars
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add vehicles*.json
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

  rebuild_website:
    name: "Rebuild website"
    runs-on: ubuntu-latest
    needs: ["Update data"]
    steps:
      - uses: "actions/checkout@v3"

      - name: Launch the website rebuild workflow
        run: gh workflow run website.yml
        env:
          GH_TOKEN: ${{ github.token }}
